language: node_js

node_js:
  - "6"
  
branches:
  only:
  - master

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < /home/travis/build/sudzy-group/pouchable/coverage/lcov.info